#!/usr/bin/env bash
set -euo pipefail

APP_NAME="Boba Factory Installer"
APP_VERSION="2.2.0"

REPO_URL_DEFAULT="https://github.com/BobaDev-Factory/boba-factory.git"
TARGET_ROOT_DEFAULT="$HOME/.openclaw/workspace"
TARGET_REPO_DEFAULT="$TARGET_ROOT_DEFAULT/boba-factory"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IN_REPO_MODE=0

# ---------- UI ----------
if [[ -t 1 ]]; then
  C_RESET='\033[0m'
  C_BOLD='\033[1m'
  C_DIM='\033[2m'
  C_BLUE='\033[34m'
  C_CYAN='\033[36m'
  C_GREEN='\033[32m'
  C_YELLOW='\033[33m'
  C_RED='\033[31m'
else
  C_RESET=''; C_BOLD=''; C_DIM=''; C_BLUE=''; C_CYAN=''; C_GREEN=''; C_YELLOW=''; C_RED=''
fi

banner() {
  echo -e "${C_CYAN}${C_BOLD}"
  cat <<'ASCII'
 ____        _            _____          _
| __ )  ___ | |__   __ _ |  ___|_ _  ___| |_ ___  _ __ _   _
|  _ \ / _ \| '_ \ / _` || |_ / _` |/ __| __/ _ \| '__| | | |
| |_) | (_) | |_) | (_| ||  _| (_| | (__| || (_) | |  | |_| |
|____/ \___/|_.__/ \__,_||_|  \__,_|\___|\__\___/|_|   \__, |
                                                        |___/
ASCII
  echo -e "${C_RESET}${C_BOLD}${APP_NAME}${C_RESET} ${C_DIM}v${APP_VERSION}${C_RESET}"
  echo
}

step() { echo -e "${C_BLUE}${C_BOLD}▶${C_RESET} ${C_BOLD}$1${C_RESET}"; }
info() { echo -e "${C_DIM}• $1${C_RESET}"; }
ok()   { echo -e "${C_GREEN}✓ $1${C_RESET}"; }
warn() { echo -e "${C_YELLOW}⚠ $1${C_RESET}"; }
err()  { echo -e "${C_RED}✗ $1${C_RESET}"; }

prompt() {
  local var_name="$1"; shift
  local label="$1"; shift
  local default_value="${1:-}"
  local value
  if [[ -n "$default_value" ]]; then
    read -r -p "$label [$default_value]: " value
    value="${value:-$default_value}"
  else
    read -r -p "$label: " value
  fi
  printf -v "$var_name" '%s' "$value"
}

prompt_secret() {
  local var_name="$1"; shift
  local label="$1"; shift
  local value
  echo -e "${C_DIM}(saisie masquée — aucun caractère affiché)${C_RESET}"
  read -r -s -p "$label: " value
  echo
  printf -v "$var_name" '%s' "$value"
}

if [[ "${1:-}" == "--in-repo" ]]; then
  IN_REPO_MODE=1
  shift
fi

bootstrap_repo_if_needed() {
  local repo_url="${BOBA_FACTORY_REPO_URL:-$REPO_URL_DEFAULT}"
  local target_root="${BOBA_FACTORY_HOME:-$TARGET_ROOT_DEFAULT}"
  local target_repo="${BOBA_FACTORY_REPO_DIR:-$TARGET_REPO_DEFAULT}"

  mkdir -p "$target_root"

  step "Bootstrap repository"
  if [[ ! -d "$target_repo/.git" ]]; then
    info "Clone vers: $target_repo"
    git clone "$repo_url" "$target_repo"
  else
    info "Repo déjà présent: $target_repo"
    info "Mise à jour locale"
    git -C "$target_repo" pull --ff-only || warn "Impossible de pull (continuation locale)"
  fi

  info "Relance de l'install depuis le repo cible"
  exec "$target_repo/install.sh" --in-repo "$@"
}

# Standalone mode: run from anywhere, normalize to ~/.openclaw/workspace/boba-factory
if [[ "$IN_REPO_MODE" -eq 0 ]]; then
  if [[ ! -f "$SCRIPT_DIR/BOOT.md" || ! -d "$SCRIPT_DIR/templates/workspace" ]]; then
    bootstrap_repo_if_needed "$@"
  fi

  TARGET_REPO="${BOBA_FACTORY_REPO_DIR:-$TARGET_REPO_DEFAULT}"
  if [[ "$SCRIPT_DIR" != "$TARGET_REPO" ]]; then
    bootstrap_repo_if_needed "$@"
  fi
fi

REPO_ROOT="$SCRIPT_DIR"
CONFIG_DIR="$REPO_ROOT/config"
CONFIG_FILE="$CONFIG_DIR/local.env"
TEMPLATES_DIR="$REPO_ROOT/templates/workspace"
mkdir -p "$CONFIG_DIR"

banner
step "Configuration"

DEFAULT_WORKSPACE="$HOME/.openclaw/workspace"
prompt WORKSPACE_PATH "OpenClaw workspace path" "$DEFAULT_WORKSPACE"
prompt BF_OWNER_NAME "Nom humain (owner Boba Factory)" "BobaMaster"
prompt BF_MAIN_AGENT_NAME "Nom de l'agent principal" "Boba"
prompt JIRA_BASE_URL "Jira base URL (sans slash final)" "https://bobacloud.atlassian.net"
prompt JIRA_PROJECT_KEY "Jira project key" "BDF"
prompt GITHUB_ORG "GitHub organization" "BobaDev-Factory"
prompt GITHUB_TOKEN_MODE "GitHub token source (gh|env|none)" "gh"
prompt JIRA_EMAIL "Jira email/login (optionnel)" ""
prompt_secret JIRA_TOKEN "Jira token (optionnel, masqué)"
prompt_secret GITHUB_PAT "GitHub PAT (optionnel, masqué)"

step "Apply configuration"
mkdir -p "$WORKSPACE_PATH"
AGENTS_FILE="$WORKSPACE_PATH/AGENTS.md"
BOOT_PATH="$REPO_ROOT/BOOT.md"

cat > "$CONFIG_FILE" <<CFG
# Local config generated by install.sh (gitignored)
BF_OWNER_NAME=$BF_OWNER_NAME
BF_MAIN_AGENT_NAME=$BF_MAIN_AGENT_NAME
JIRA_BASE_URL=$JIRA_BASE_URL
JIRA_PROJECT_KEY=$JIRA_PROJECT_KEY
JIRA_EMAIL=$JIRA_EMAIL
JIRA_TOKEN=$JIRA_TOKEN
GITHUB_PAT=$GITHUB_PAT
GITHUB_ORG=$GITHUB_ORG
GITHUB_TOKEN_MODE=$GITHUB_TOKEN_MODE
WORKSPACE_PATH=$WORKSPACE_PATH
CFG
chmod 600 "$CONFIG_FILE"

GITIGNORE_FILE="$REPO_ROOT/.gitignore"
touch "$GITIGNORE_FILE"
for line in "config/*" "!config/.gitkeep" "projects/*" "!projects/.gitkeep" "projects/*/.boba/ACTIVE_CONTEXT.json" "projects/*/.boba/LOCK"; do
  grep -qxF "$line" "$GITIGNORE_FILE" || echo "$line" >> "$GITIGNORE_FILE"
done
mkdir -p "$REPO_ROOT/projects"
touch "$REPO_ROOT/projects/.gitkeep" "$REPO_ROOT/config/.gitkeep"

BOOT_BEGIN="<!-- BOBA_FACTORY:GENERATED:START -->"
BOOT_END="<!-- BOBA_FACTORY:GENERATED:END -->"
GENERATED_BOOT=$(cat <<EOB
$BOOT_BEGIN
- Owner: **$BF_OWNER_NAME**
- Main agent: **$BF_MAIN_AGENT_NAME**
- GitHub org: \`$GITHUB_ORG\`
- Jira: \`$JIRA_BASE_URL\` (project \`$JIRA_PROJECT_KEY\`)
$BOOT_END
EOB
)

if grep -q "$BOOT_BEGIN" "$BOOT_PATH"; then
  awk -v start="$BOOT_BEGIN" -v end="$BOOT_END" -v repl="$GENERATED_BOOT" '
    BEGIN{inblk=0}
    $0==start{print repl; inblk=1; next}
    $0==end{inblk=0; next}
    !inblk{print}
  ' "$BOOT_PATH" > "$BOOT_PATH.tmp" && mv "$BOOT_PATH.tmp" "$BOOT_PATH"
else
  printf "\n%s\n" "$GENERATED_BOOT" >> "$BOOT_PATH"
fi

AG_BEGIN="<!-- BOBA_FACTORY:START -->"
AG_END="<!-- BOBA_FACTORY:END -->"
mkdir -p "$(dirname "$AGENTS_FILE")"
touch "$AGENTS_FILE"
POINTER_BLOCK=$(sed "s|{{BOOT_PATH}}|$BOOT_PATH|g" "$TEMPLATES_DIR/AGENTS.block.md")
POINTER_FULL="$AG_BEGIN
$POINTER_BLOCK
$AG_END"

if grep -q "$AG_BEGIN" "$AGENTS_FILE"; then
  awk -v start="$AG_BEGIN" -v end="$AG_END" -v repl="$POINTER_FULL" '
    BEGIN{inblk=0}
    $0==start{print repl; inblk=1; next}
    $0==end{inblk=0; next}
    !inblk{print}
  ' "$AGENTS_FILE" > "$AGENTS_FILE.tmp" && mv "$AGENTS_FILE.tmp" "$AGENTS_FILE"
else
  printf "\n%s\n" "$POINTER_FULL" >> "$AGENTS_FILE"
fi

echo
ok "Installation terminée"
info "Config: $CONFIG_FILE"
info "BOOT updated: $BOOT_PATH"
info "AGENTS pointer: $AGENTS_FILE"
