#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$REPO_ROOT/config"
CONFIG_FILE="$CONFIG_DIR/local.env"
TEMPLATES_DIR="$REPO_ROOT/templates/workspace"

mkdir -p "$CONFIG_DIR"

prompt() {
  local var_name="$1"; shift
  local label="$1"; shift
  local default_value="${1:-}"
  local value
  if [[ -n "$default_value" ]]; then
    read -r -p "$label [$default_value]: " value
    value="${value:-$default_value}"
  else
    read -r -p "$label: " value
  fi
  printf -v "$var_name" '%s' "$value"
}

prompt_secret() {
  local var_name="$1"; shift
  local label="$1"; shift
  local value
  read -r -s -p "$label: " value
  echo
  printf -v "$var_name" '%s' "$value"
}

echo "== Boba Factory installer =="

DEFAULT_WORKSPACE="$HOME/.openclaw/workspace"
prompt WORKSPACE_PATH "OpenClaw workspace path" "$DEFAULT_WORKSPACE"
prompt BF_OWNER_NAME "Nom humain (owner Boba Factory)" "BobaMaster"
prompt BF_MAIN_AGENT_NAME "Nom de l'agent principal" "Boba"
prompt JIRA_BASE_URL "Jira base URL (sans slash final)" "https://bobacloud.atlassian.net"
prompt JIRA_PROJECT_KEY "Jira project key" "BDF"
prompt GITHUB_ORG "GitHub organization" "BobaDev-Factory"
prompt GITHUB_TOKEN_MODE "GitHub token source (gh|env|none)" "gh"
prompt JIRA_EMAIL "Jira email/login (optionnel)" ""
prompt_secret JIRA_TOKEN "Jira token (optionnel, masqué)"

mkdir -p "$WORKSPACE_PATH"
AGENTS_FILE="$WORKSPACE_PATH/AGENTS.md"
BOOT_PATH="$REPO_ROOT/BOOT.md"

cat > "$CONFIG_FILE" <<CFG
# Local config generated by install.sh (gitignored)
BF_OWNER_NAME=$BF_OWNER_NAME
BF_MAIN_AGENT_NAME=$BF_MAIN_AGENT_NAME
JIRA_BASE_URL=$JIRA_BASE_URL
JIRA_PROJECT_KEY=$JIRA_PROJECT_KEY
JIRA_EMAIL=$JIRA_EMAIL
JIRA_TOKEN=$JIRA_TOKEN
GITHUB_ORG=$GITHUB_ORG
GITHUB_TOKEN_MODE=$GITHUB_TOKEN_MODE
WORKSPACE_PATH=$WORKSPACE_PATH
CFG
chmod 600 "$CONFIG_FILE"

# Ensure config is gitignored
GITIGNORE_FILE="$REPO_ROOT/.gitignore"
touch "$GITIGNORE_FILE"
for line in "config/*" "!config/.gitkeep" "projects/*" "!projects/.gitkeep"; do
  grep -qxF "$line" "$GITIGNORE_FILE" || echo "$line" >> "$GITIGNORE_FILE"
done
mkdir -p "$REPO_ROOT/projects"
touch "$REPO_ROOT/projects/.gitkeep" "$REPO_ROOT/config/.gitkeep"

# Inject/update BOOT.md generated section
BOOT_BEGIN="<!-- BOBA_FACTORY:GENERATED:START -->"
BOOT_END="<!-- BOBA_FACTORY:GENERATED:END -->"
GENERATED_BOOT=$(cat <<EOB
$BOOT_BEGIN
## Installed configuration (generated)

- Owner: **$BF_OWNER_NAME**
- Main agent: **$BF_MAIN_AGENT_NAME**
- GitHub org: \
  \`$GITHUB_ORG\`
- Jira: \`$JIRA_BASE_URL\` (project \`$JIRA_PROJECT_KEY\`)

## Agent routing baseline

- Orchestrator ($BF_MAIN_AGENT_NAME): planning, gating, integration, final decision
- Spec Agent (Atlas): scope + acceptance criteria
- Code Agents (Forge-Backend / Forge-Frontend): implementation
- Review Agent (Sentinel): bugs/security/perf/style
- Test Agent (Pulse): lint/tests/typecheck/e2e evidence
- Doc Agent (Scribe): docs/runbook/changelog

Model policy is defined by BOOT.md runtime instructions and can be adjusted per mission.
$BOOT_END
EOB
)

if grep -q "$BOOT_BEGIN" "$BOOT_PATH"; then
  awk -v start="$BOOT_BEGIN" -v end="$BOOT_END" -v repl="$GENERATED_BOOT" '
    BEGIN{inblk=0}
    $0==start{print repl; inblk=1; next}
    $0==end{inblk=0; next}
    !inblk{print}
  ' "$BOOT_PATH" > "$BOOT_PATH.tmp" && mv "$BOOT_PATH.tmp" "$BOOT_PATH"
else
  printf "\n%s\n" "$GENERATED_BOOT" >> "$BOOT_PATH"
fi

# Inject/update AGENTS.md pointer block
mkdir -p "$(dirname "$AGENTS_FILE")"
touch "$AGENTS_FILE"
AG_BEGIN="<!-- BOBA_FACTORY:START -->"
AG_END="<!-- BOBA_FACTORY:END -->"
POINTER_BLOCK=$(sed "s|{{BOOT_PATH}}|$BOOT_PATH|g" "$TEMPLATES_DIR/AGENTS.block.md")
POINTER_FULL="$AG_BEGIN
$POINTER_BLOCK
$AG_END"

if grep -q "$AG_BEGIN" "$AGENTS_FILE"; then
  awk -v start="$AG_BEGIN" -v end="$AG_END" -v repl="$POINTER_FULL" '
    BEGIN{inblk=0}
    $0==start{print repl; inblk=1; next}
    $0==end{inblk=0; next}
    !inblk{print}
  ' "$AGENTS_FILE" > "$AGENTS_FILE.tmp" && mv "$AGENTS_FILE.tmp" "$AGENTS_FILE"
else
  printf "\n%s\n" "$POINTER_FULL" >> "$AGENTS_FILE"
fi

echo
echo "Install complete"
echo "- Config: $CONFIG_FILE"
echo "- BOOT updated: $BOOT_PATH"
echo "- AGENTS pointer ensured: $AGENTS_FILE"
